defaults: &defaults
  docker:
    - image: circleci/node:8.10

version: 2

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-workspace
      - restore_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-workspace
      - run: yarn run validate
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-workspace
      - run: cp .npmrc-ci .npmrc
      - run: yarn run release

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - install
            - test
          filters:
            branches:
              only:
                - master
