defaults: &defaults
  docker:
    - image: circleci/node:8.10

version: 2

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          keys:
          - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - yarn-cache-{{ .Branch }}
          - yarn-cache-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: /tmp/workspace

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: yarn run validate

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          cp .npmrc-ci .npmrc
          yarn run release

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - deploy:
          requires:
            - checkout
            - test
          filters:
            branches:
              only:
                - master
